Loading
onja-org/vamalaka-fannar pull request #10
Opened 2021-08-02 06:39 UTC by lightme-fan

Hey everyone,

I have just finished working on the loading or pending indicator. Please have a look at it.

Thanks in advance

- Branch: [https://github.com/onja-org/vamalaka-fannar/tree/loading](https://github.com/onja-org/vamalaka-fannar/tree/loading)
- ClickUp: [https://app.clickup.com/t/45e3jw](https://app.clickup.com/t/45e3jw)
- Refs: #45e3jw

2021-08-02 06:55 UTC, Tiaraha-funny commented on src/components/Loading/Loading.tsx
> +  source: any
Maybe we shouldn't have "any" type

2021-08-02 12:50 UTC, andrzej-onja requested changes

2021-08-02 12:50 UTC, andrzej-onja commented on src/components/Loading/Loading.tsx
> +`
have you used svg from the clickup ticket attachment ? it was already animating

2021-08-02 12:50 UTC, andrzej-onja commented on src/components/Loading/icons/extremely-samll.svg
> +<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
please use one react component for all sizes that wraps svg and passes dimensions as a prop

2021-08-02 12:50 UTC, andrzej-onja commented on src/components/Loading/Loading.tsx
> +export const Loading: FC<SourceType> = ({ source }) => {
rename to LoadingIndicator
- remove source prop and create size  prop
 size: 'xl'| "lg"  etc. similar to what we have in mediaqueries.ts

2021-08-03 06:52 UTC, andrzej-onja approved these changes

2021-08-03 06:53 UTC, Tiaraha-funny approved these changes

2021-08-03 06:53 UTC, mitia-anah approved these changes

2021-08-03 06:54 UTC, merged