Rosny user widget
onja-org/vamalaka-fannar pull request #44
Opened 2021-12-11 13:07 UTC by mitia-anah

2021-12-17 05:44 UTC, andrzej-onja commented on src/pages/UserWidget/UserWidget.tsx
> +          Adolfia
This information should be derived from the props and dynamically passed based on the UserState

2021-12-17 05:44 UTC, andrzej-onja commented on src/pages/LoginPage.tsx
> +    // error?.message?.toString()?.indexOf('CODE:EU12') > -1
why all those conditions were commented out ?

2021-12-17 05:44 UTC, andrzej-onja commented on src/pages/UserWidget/UserWidget.tsx
> +          Adolfia
userSelector should have been used

2021-12-17 05:44 UTC, andrzej-onja commented on src/pages/UserWidget/UserWidget.tsx
> +        </LogoutButton>
logout logic is missing - user state should be cleared

2021-12-17 05:44 UTC, andrzej-onja commented on src/paths/index.tsx
> +  USER_WIDGET = '/user-widget',
This was suppose to be shown on hover not as a separate page

2022-03-02 09:41 UTC, andrzej-onja requested changes

2022-03-02 09:41 UTC, andrzej-onja commented on package.json
> +    "react-widgets": "^5.8.3",
those 2 are not used, remove

2022-03-02 09:41 UTC, andrzej-onja commented on .vscode/launch.json
> +}
why do we need this change ?

2022-03-02 09:41 UTC, andrzej-onja commented on src/components/HeaderNavLink/List.tsx
> +export const List = styled.li`
if you change to li -list item, `List` name dest make sense. Rename it if this component is used as List item

2022-03-02 09:41 UTC, andrzej-onja commented on src/components/LoginForm/LoginForm.tsx
> +  onSubmit: (username: string, password: string, photo: any) => void
type photo

2022-03-02 09:41 UTC, andrzej-onja commented on src/components/UserWidget/UserWidget.tsx
> +  const unToggle = () => setIsShown(false);
```
toggle
Computing
switch from one effect, feature, or state to another by using a toggle.
```

those names are not reflecting the action

replace to open, close or show and hide

2022-03-02 09:41 UTC, andrzej-onja commented on src/components/UserWidget/UserWidget.tsx
> +  const userPhoto = "http://192.168.1.46:4000/uploads/" + user.photos[0]?.url;
rename to userPhotoUrl

store `http://192.168.1.46:4000` in global `const BASE_ENDPOINT`

2022-03-02 09:41 UTC, andrzej-onja commented on src/components/UserWidget/UserWidget.tsx
> +  const userOffer = useSelector(userOfferSelector);
userOffer**s**

2022-03-02 09:41 UTC, andrzej-onja commented on src/components/UserWidget/UserWidgetStyles.tsx
> +
just put those inside userWidget and remove the file

2022-03-02 09:41 UTC, andrzej-onja commented on src/graphqlHelper.ts
> +        id: "${id}",
why id is here ?

2022-03-02 09:41 UTC, andrzej-onja commented on src/pages/LoginPage.tsx
> +        id: ''
why photos and id was added here ?

2022-03-02 09:41 UTC, andrzej-onja commented on src/redux/slices/userOfferSlice.tsx
> +      message: 'Failed to fetch userOffer.',
s

2022-03-02 09:41 UTC, andrzej-onja commented on src/redux/slices/userOfferSlice.tsx
> +>('getUserAds/fetch', async (fetchUserOffer, thunkApi) => {
fetchUserOffer**s** plural

2022-03-02 09:41 UTC, andrzej-onja commented on src/redux/slices/userOfferSlice.tsx
> +export default userOfferSlice.reducer
rename everywhere Offer to offer**s**

2022-03-02 09:41 UTC, andrzej-onja commented on src/redux/slices/userSlice.tsx
> +interface PhotoProps {
just rename to Photo

Props is used for react component props - properties

2022-03-02 09:41 UTC, andrzej-onja commented on src/redux/slices/userSlice.tsx
> +    registerMutation(username, password, email, confirmPassword, role, id)
id ?

2022-03-02 11:13 UTC, mitia-anah commented on src/redux/slices/userSlice.tsx
> +    registerMutation(username, password, email, confirmPassword, role, id)
This Id is the user's id. I should not use it on the register but if I remove it then it will throw errors.

2022-03-02 11:22 UTC, mitia-anah commented on src/pages/LoginPage.tsx
> +        id: ''
For me to be able to fetch them from the user. I can't access them from the user if I didn't add them there.

2022-03-02 11:24 UTC, mitia-anah commented on src/graphqlHelper.ts
> +        id: "${id}",
I added it here as a part of the property of the user.

2022-03-02 11:52 UTC, mitia-anah commented on .vscode/launch.json
> +}
I didn't see that, I think it was something that Fanilo tried when I asked him to help me to debug my code.

2022-03-02 12:13 UTC, lightme-fan commented
Fix all Andrej's comments, please.

2022-03-03 05:23 UTC, mitia-anah commented
> Fix all Andrej's comments, please.

2022-03-07 07:44 UTC, andrzej-onja commented on src/App.tsx
> +// import { UserWidget } from "./components/UserWidget/UserWidget";
remove the commented out code

2022-03-07 07:44 UTC, andrzej-onja commented on src/containers/RegisterAccountContainer.tsx
> +          id: event.currentTarget.id
Photos and Id are not required to register a user. Please remove

2022-03-07 13:25 UTC, lightme-fan approved these changes
Nice

2022-03-09 05:04 UTC, merged