feat(Adds Form Register Component): Created a component and its story
onja-org/vamalaka-fannar pull request #8
Opened 2021-07-27 06:53 UTC by Tiaraha-funny

Hey team,

I have created this form register branch to handle the registration component. I think t is ready to be reviewed so please have a look at it and leave any comment for it to be improved.

Click up link: https://app.clickup.com/t/41k87k
Refs: #41k87k 

Thanks a lot.

2021-07-27 11:14 UTC, andrzej-onja requested changes

2021-07-27 11:14 UTC, andrzej-onja commented on src/components/Buttons/Buttons.tsx
> +  onClick?: (event: React.FormEvent<HTMLFormElement>) => any
Event will not always be a form event... For now its fine but will have to be changed in the future

2021-07-27 11:14 UTC, andrzej-onja commented on src/components/Buttons/Buttons.tsx
>    learnEnabled?: boolean
rename learnEnabled to isPrimary

2021-07-27 11:14 UTC, andrzej-onja commented on src/components/InputName/InputName.tsx
> +        <div className='error'>{errorMes} </div>
No className assignments, pleases use styled components and pass props to them

2021-07-27 11:14 UTC, andrzej-onja commented on src/mediaQuery/mediaQueries.tsx
> +}
we are using this version https://codesandbox.io/s/media-queries-in-styled-components-typescript-forked-o4tt0 . Please change it. Its based on the article but heavily modified

2021-07-28 05:29 UTC, lightme-fan reviewed
Perhaps, you'd better fix Andrej's comments. Thanks

2021-07-28 10:41 UTC, lightme-fan commented on src/components/InputName/InputName.tsx
> +  .noPlaceholder {
You shouldn't have a className

2021-07-28 10:41 UTC, lightme-fan commented on src/components/InputName/InputName.tsx
>    .small {
Please, use styled component.

2021-07-28 10:41 UTC, lightme-fan commented on src/components/InputName/InputName.tsx
>  const InputElement = styled.input`
If there is nothing in this style, remove it.

2021-07-30 08:05 UTC, lightme-fan reviewed
Looking good!

2021-07-30 08:17 UTC, lightme-fan approved these changes

2021-07-30 08:19 UTC, mitia-anah approved these changes

2021-07-30 08:54 UTC, andrzej-onja commented on src/components/Buttons/Buttons.tsx
> +      isPrimary={isPrimary ? true : false}
you can just pass isPrimary

2021-07-30 08:54 UTC, andrzej-onja commented on src/components/Buttons/Buttons.tsx
> +      disabled={false}
why false is hardcoded ?

2021-07-30 08:54 UTC, andrzej-onja commented on src/components/RegisterForm/formRegister.tsx
> +import React, { useState } from 'react'
align with naming convention

2021-07-30 08:54 UTC, andrzej-onja commented on src/components/RegisterForm/formRegister.tsx
> +import React, { useState } from 'react'
RegisterForm/formRegister.tsx 
RegisterForm/RegisterForm.tsx

2021-07-30 08:54 UTC, andrzej-onja commented on src/components/RegisterForm/formRegister.tsx
> +  condition,
please implement props as discussed
onSubmit,
errors:

where errrors is an object of type  {password:String, email:string, username:string}

2021-08-02 12:42 UTC, andrzej-onja commented on src/components/Buttons/Buttons.tsx
> +        {!isPrimary && <img src={icon} alt='icon' />}
icons can also be in primary variant

2021-08-02 12:42 UTC, andrzej-onja commented on src/components/RegisterForm/RegisterForm.tsx
> +    isValid: false,
isvalid unused, remove

2021-08-02 12:42 UTC, andrzej-onja commented on src/components/RegisterForm/RegisterForm.tsx
> +  const [valid, setValid] = React.useState({
I think this should be renamed from valid to something more general like inputInfo

2021-08-02 12:42 UTC, andrzej-onja commented on src/components/RegisterForm/RegisterForm.tsx
> +        value={valid.userName}
valid.userName ?? this is email

2021-08-03 10:55 UTC, andrzej-onja requested changes

2021-08-03 10:55 UTC, andrzej-onja commented on src/components/RegisterForm/RegisterForm.tsx
> +      correctEmail: true,
correctEmail is unused, remove

2021-08-04 05:28 UTC, andrzej-onja approved these changes

2021-08-04 05:28 UTC, andrzej-onja commented on src/components/Buttons/Buttons.tsx
> +  type,
type is unused ?

2021-08-04 05:28 UTC, andrzej-onja commented on src/components/Buttons/Buttons.tsx
>    ...props
remove ...props , explicitly pass all props

2021-08-04 05:28 UTC, andrzej-onja commented on src/components/Buttons/Buttons.tsx
>    label?: string
make label mandatory

2021-08-04 05:28 UTC, andrzej-onja commented on src/components/RegisterForm/RegisterForm.tsx
> +          icon={icon}
hardcode icon we dont need to pass it as a prop to the form

2021-08-04 07:55 UTC, merged